export const COLORS = {

  PRIMARY: '#007AFF',
  SECONDARY: '#000000',
  SUCCESS: '#4CAF50',
  
  TEXT_PRIMARY: '#000000',
  TEXT_SECONDARY: '#333333',
  TEXT_TERTIARY: '#666666',
  TEXT_DISABLED: '#888888',
  TEXT_WHITE: '#FFFFFF',
  
  BACKGROUND_WHITE: '#FFFFFF',
  BACKGROUND_LIGHT: '#F8F9FA',
  BACKGROUND_BLUE: '#E3F2FD',
  BACKGROUND_DISABLED: '#CCCCCC',
  
  BORDER_LIGHT: '#DDDDDD',
  BORDER_MEDIUM: '#CCCCCC',
  
  ERROR: '#FF3333',
} as const;