export const MOTION_DETECTION = {
  UPDATE_INTERVAL_MS: 100,
  SAMPLE_BUFFER_SIZE: 50,
  MINIMUM_REP_INTERVAL_MS: 500,
  DEFAULT_THRESHOLD: 1.5,
  THRESHOLD_RANGE: { 
    MINIMUM: 0.5, 
    MAXIMUM: 3.0 
  },
  CALIBRATION_SAMPLE_COUNT: 30,
  CALIBRATION_COUNTDOWN_SECONDS: 3
} as const;

export const WORKOUT_LIMITS = {
  SETS: {
    MINIMUM: 1,
    MAXIMUM: 20
  },
  REPS: {
    MINIMUM: 1,
    MAXIMUM: 999
  },
  WEIGHT: {
    MINIMUM: 0,
    MAXIMUM: 9999,
    DEFAULT_INCREMENT: 2.5
  },
  DURATION: {
    MINIMUM_SECONDS: 0,
    MAXIMUM_SECONDS: 3600,
    DEFAULT_INCREMENT_SECONDS: 15
  },
  REST_TIME: {
    MINIMUM_SECONDS: 0,
    MAXIMUM_SECONDS: 600,
    DEFAULT_SECONDS: 60,
    INCREMENT_SECONDS: 15
  }
} as const;

export const CAMERA_CONFIG = {
  PHOTO_QUALITY: 0.8,
  HEADER_TOP_PADDING: 60
} as const;

export const REST_TIMER = {
  QUICK_ADD_OPTIONS_SECONDS: [15, 30, 60],
  WARNING_THRESHOLD_SECONDS: 30,
  CRITICAL_THRESHOLD_SECONDS: 10,
  PULSE_ANIMATION_DURATION_MS: 300
} as const;

export const UI_CONSTANTS = {
  CHART_WIDTH_OFFSET: 48,
  CHART_HEIGHT: 220,
  TIMER_FONT_SIZE: 48,
  PROGRESS_ANIMATION_DURATION_MS: 300
} as const;