export const DIMENSIONS = {

  BUTTON_HEIGHT: 50,
  BUTTON_BORDER_RADIUS: 25,
  BUTTON_PADDING_VERTICAL: 16,
  BUTTON_PADDING_HORIZONTAL: 24,
  
  SPACING_SMALL: 8,
  SPACING_MEDIUM: 16,
  SPACING_LARGE: 24,
  SPACING_EXTRA_LARGE: 30,
  SPACING_HUGE: 40,
  
  FONT_SIZE_SMALL: 14,
  FONT_SIZE_MEDIUM: 16,
  FONT_SIZE_LARGE: 18,
  FONT_SIZE_TITLE: 24,
  FONT_SIZE_HEADER: 28,
  
  ICON_SIZE_SMALL: 16,
  ICON_SIZE_MEDIUM: 32,
  ICON_SIZE_LARGE: 60,
} as const;